version: '3.4'

services:
  web:
    image: kfdrc/kf-api-study-creator:latest
    env_file: docker.env
    environment:
      - DATASERVICE_URL=http://dataservice
      - FEAT_DATASERVICE_CREATE_STUDIES=True
      - FEAT_DATASERVICE_UPDATE_STUDIES=True
      - ALLOWED_HOSTS=web
      - DJANGO_SETTINGS_MODULE=creator.settings.development
      - PG_HOST=postgres
      # Options are: DATASERVICE, url of dataservice, or FAKE
      - PRELOAD_DATA=FAKE
      - DEVELOPMENT_ENDPOINTS=True
      - DEVELOP=True
      - EMAIL_HOST=email
      - EMAIL_PORT=1025
    ports:
      - '5002:8080'
    depends_on:
      - postgres
      - redis
  worker:
    image: kfdrc/kf-api-study-creator:latest
    env_file: docker.env
    command: '/app/bin/dev_worker.sh'
    environment:
      - DJANGO_SETTINGS_MODULE=creator.settings.development
    depends_on:
      - postgres
      - redis
      - web
  scheduler:
    image: kfdrc/kf-api-study-creator:latest
    env_file: docker.env
    command: './manage.py rqscheduler -i 5'
    environment:
      - DJANGO_SETTINGS_MODULE=creator.settings.development
    depends_on:
      - postgres
      - redis
      - web
  postgres:
    image: circleci/postgres:11.1
    env_file: docker.env
    environment:
      - POSTGRES_DB=study-creator
      - POSTGRES_USER=study-creator
      - POSTGRES_PASSWORD=password
  redis:
    image: circleci/redis:latest
  app:
    image: circleci/node:12
    command: bash -c 'cd /app && yarn start'
    ports:
      - 3000:3000
    environment:
      - CI=true
      - REACT_APP_STUDY_API=http://web:8080
      - REACT_APP_AUTH0_DOMAIN=kids-first.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=00000000000000000000000000000000
      - REACT_APP_AUTH0_REDIRECT_URI=http://app:3000/callback
      - REACT_APP_AUTH0_AUD=https://kf-study-creator.kidsfirstdrc.org
      - SKIP_PREFLIGHT_CHECK=true
    volumes:
      - bundle:/app
  cypress:
    image: cypress/browsers:node13.6.0-chrome80-ff72
    container_name: cypress
    environment:
      - CYPRESS_baseUrl=http://app:3000
      - CYPRESS_REACT_APP_STUDY_API=http://web:8080
      - CYPRESS_DEV_ENDPOINT=http://web:8080/__dev
    depends_on:
      - app
      - web
      - worker
      - scheduler
      - postgres
      - redis
    command: /bin/bash -c 'yarn run cypress install && yarn run cypress run --browser chrome'
    working_dir: /app
    volumes:
      - bundle:/app
  dataservice:
    image: kfdrc/kf-api-dataservice:latest
    command: /bin/ash -c "sleep 5; ./bin/run.sh"
    environment:
      - FLASK_CONFIG=development
      - PG_NAME=dataservice
      - PG_HOST=dataservice-pg
    depends_on:
      - dataservice-pg
  dataservice-pg:
    image: circleci/postgres:11.1
    environment:
      - POSTGRES_DB=dataservice
  email:
    image: reachfive/fake-smtp-server
    env_file: docker.env
    ports:
      - '1080:1080'
networks:
  default:
    external:
      name: kf-data-stack
volumes:
  bundle:
    external: true
