[build.environment]
  REACT_APP_DEV_BAR=""
  REACT_APP_AUTH0_DOMAIN="kids-first.auth0.com"

[context.awsprod]
  publish = "build/"

[context.awsprod.environment]
  REACT_APP_ENV = "prd"
  REACT_APP_AUTH0_REDIRECT_URI = "https://data-tracker.kidsfirstdrc.org/callback"
  REACT_APP_AUTH0_LOGOUT_REDIRECT_URI = "https://data-tracker.kidsfirstdrc.org/logout"
  REACT_APP_STUDY_API = "https://kf-api-study-creator.kidsfirstdrc.org"
  REACT_APP_COORD_API = "https://kf-release-coord.kidsfirstdrc.org"
  REACT_APP_COORD_UI = "https://kf-ui-release-coordinator.kidsfirstdrc.org/"
  REACT_APP_PRIMARY_HOST = "https://data-tracker.kidsfirstdrc.org"
  REACT_APP_REDIRECT_TO_PRIMARY = "true"

[context.production]
  publish = "build/"
  ignore = "./build_check.sh"

[context.production.environment]
  REACT_APP_ENV = "qa"
  REACT_APP_AUTH0_REDIRECT_URI = "https://data-tracker-qa.kidsfirstdrc.org/callback"
  REACT_APP_AUTH0_LOGOUT_URI = "https://data-tracker-qa.kidsfirstdrc.org/logout"
  REACT_APP_PRIMARY_HOST = "https://data-tracker-qa.kidsfirstdrc.org"
  REACT_APP_REDIRECT_TO_PRIMARY = "true"
  REACT_APP_STUDY_API = "https://kf-api-study-creator-qa.kidsfirstdrc.org"
  REACT_APP_COORD_API = "https://kf-release-coord-qa.kidsfirstdrc.org"
  REACT_APP_COORD_UI = "https://kf-ui-release-coordinator-qa.kidsfirstdrc.org/"
  REACT_APP_AMPLITUDE_KEY = "0dd725bc46163f46b3abad77d4e9590c"

[context.deploy-preview]
  publish = "build/"
  command = "REACT_APP_AUTH0_REDIRECT_URI=$DEPLOY_PRIME_URL/callback REACT_APP_AUTH0_LOGOUT_REDIRECT_URI=$DEPLOY_PRIME_URL/logout yarn build"

[context.deploy-preview.environment]
  REACT_APP_ENV = "dev"
  REACT_APP_STUDY_API = "https://kf-api-study-creator-dev.kidsfirstdrc.org"
  REACT_APP_COORD_API = "https://kf-release-coord-dev.kidsfirstdrc.org"
  REACT_APP_COORD_UI = "https://kf-ui-release-coordinator-dev.kidsfirstdrc.org/"
  REACT_APP_AMPLITUDE_KEY = "0dd725bc46163f46b3abad77d4e9590c"

[context.branch-deploy]
  publish = "build/"
  command = "REACT_APP_AUTH0_REDIRECT_URI=$DEPLOY_PRIME_URL/callback REACT_APP_AUTH0_LOGOUT_REDIRECT_URI=$DEPLOY_PRIME_URL/logout yarn build"

[context.branch-deploy.environment]
  REACT_APP_ENV = "dev"
  REACT_APP_STUDY_API = "https://kf-study-creator-dev.kidsfirstdrc.org"
  REACT_APP_COORD_API = "https://kf-release-coord-dev.kidsfirstdrc.org"
  REACT_APP_COORD_UI = "https://kf-ui-release-coordinator-dev.kidsfirstdrc.org/"
  REACT_APP_AMPLITUDE_KEY = "0dd725bc46163f46b3abad77d4e9590c"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
