/* This file will mock out calls to the browser's localStorage and pre-populate
 * it with an accessToken for an admin user
 */
import 'jest-localstorage-mock';

localStorage.setItem(
  'accessToken',
  'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJodHRwczovL2tpZHNmaXJzdGRyYy5vcmcvcGVybWlzc2lvbnMiOlsicmVhZDpmaWxlcyIsIndyaXRlOmZpbGVzIl0sImh0dHBzOi8va2lkc2ZpcnN0ZHJjLm9yZy9ncm91cHMiOlsiU0RfTUUwV01FMFciXSwiaHR0cHM6Ly9raWRzZmlyc3RkcmMub3JnL3JvbGVzIjpbIkFETUlOIl0sImlzcyI6Imh0dHBzOi8va2lkcy1maXJzdC5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDI2MjA3MDUzNjAwMDAwMDAwMCIsImF1ZCI6WyJodHRwczovL2tmLXN0dWR5LWNyZWF0b3Iua2lkc2ZpcnN0ZHJjLm9yZyIsImh0dHBzOi8va2lkcy1maXJzdC5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTAwMDAwMDAwLCJleHAiOjk5OTk5OTk5OTksImF6cCI6IkxYY1A2SVJWd1NnNk96a3FHeDlZQVNncFZkcEdnMkp1Iiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbXSwianRpIjoiYzY5ZWM5NDgtYTFjMC00YmQ1LWJjOTYtMzRmNmZhNzhkNjE2In0.Y6XuIgF5-FBxbKtIW1MNjb96TeRRPEejkoi3J3eqf5s',
);

localStorage.setItem('roles', JSON.stringify(['ADMIN']));

localStorage.setItem('groups', JSON.stringify([]));
